### ISSUE TITLE
Missing .pck File (Windows)

### ISSUE THREAD

**Issue by Tyendinaga** [nullportal/dog-and-ball#1]
The windows release of the 0.0.0 alpha appears to be missing its .pck file. Was able to fix locally by grabbing the pck file from the linux packaged version. Release version should be updated with a pck file. 

![image](https://user-images.githubusercontent.com/5892085/116178153-0c5adb00-a6e3-11eb-8e69-dfe768553bed.png)

**Comment by jm-janzen** [comment]
Added to [0.0.1](https://github.com/nullportal/dog-and-ball/releases/tag/0.0.1), but I'll go back and edit the original release, too. Thanks for the issue!
